info:
    version: ""
    title: data_source_huaweicloud_workspace_app_publishable_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-groups/{app_group_id}/publishable-app:
        GET:
            tag: Workspace
