info:
    version: ""
    title: data_source_huaweicloud_cce_chart_values
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CCE
paths:
    /v2/charts/{chart_id}/values:
        GET:
            tag: CCE
