info:
    version: ""
    title: data_source_huaweicloud_dms_kafka_volume_auto_expand_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Kafka
paths:
    /v2/{project_id}/instances/{instance_id}/auto-volume-expand:
        GET:
            tag: Kafka
