info:
    version: ""
    title: data_source_huaweicloud_apig_instance_ingress_ports
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/custom-ingress-ports:
        GET:
            tag: APIG
