info:
    version: ""
    title: data_source_huaweicloud_workspace_assist_auth_configuration_applied_objects
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v2/{project_id}/assist-auth-config/apply-objects:
        GET:
            tag: Workspace
