info:
    version: ""
    title: data_source_huaweicloud_cce_cluster_configuration_details
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CCE
paths:
    /api/v3/clusters/configuration/detail:
        GET:
            tag: CCE
