info:
    version: ""
    title: data_source_huaweicloud_enterprise_project_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: EPS
paths:
    /v1.0/enterprise-projects/configs:
        GET:
            tag: EPS
