info:
    version: ""
    title: data_source_huaweicloud_cce_autopilot_cluster_log_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CCE
paths:
    /autopilot/v3/projects/{project_id}/cluster/{cluster_id}/log-configs:
        GET:
            tag: CCE
