info:
    version: ""
    title: data_source_huaweicloud_aad_alarm_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: AAD
paths:
    /v2/aad/alarm:
        GET:
            tag: AAD
