info:
    version: ""
    title: data_source_huaweicloud_aad_domain_global_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: AAD
paths:
    /v2/aad/domains/global-config:
        GET:
            tag: AAD
