info:
    version: ""
    title: data_source_huaweicloud_rgc_external_config_rule_compliances
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: RGC
paths:
    /v1/governance/managed-accounts/{managed_account_id}/external-config-rule-compliances:
        GET:
            tag: RGC
