info:
    version: ""
    title: data_source_huaweicloud_hss_agent_auto_upgrade_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/setting/config/agent-auto-upgrade:
        GET:
            tag: HSS
