info:
    version: ""
    title: data_source_huaweicloud_waf_rules_application_types
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: WAF
paths:
    /v1/{project_id}/waf/rules/application-types:
        GET:
            tag: WAF
