info:
    version: ""
    title: data_source_huaweicloud_identitycenter_application_assignments
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IDENTITYCENTER
paths:
    /v1/instances/{instance_id}/application-assignments-for-principals:
        GET:
            tag: IDENTITYCENTER
