info:
    version: ""
    title: data_source_huaweicloud_identitycenter_application_instance_profiles
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IdentityCenter
paths:
    /v1/instances/{instance_id}/application-instances/{application_instance_id}/profiles:
        GET:
            tag: IdentityCenter
