info:
    version: ""
    title: data_source_huaweicloud_workspace_application_restricted_rules
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-center/app-restricted-rules:
        GET:
            tag: Workspace
