info:
    version: ""
    title: data_source_huaweicloud_hss_setting_alarm_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/setting/alarm-config:
        GET:
            tag: HSS
