info:
    version: ""
    title: data_source_huaweicloud_hss_honeypot_port_default_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/honeypot-port/default-config:
        GET:
            tag: HSS
