info:
    version: ""
    title: data_source_huaweicloud_rds_configurable_distributor_instances
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: RDS
paths:
    /v3/{project_id}/instances/{instance_id}/replication/distributors:
        GET:
            tag: RDS
