info:
    version: ""
    title: data_source_huaweicloud_hss_image_baseline_risk_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/image/baseline/risk-configs:
        GET:
            tag: HSS
