info:
    version: ""
    title: data_source_huaweicloud_identitycenter_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IDENTITYCENTER
paths:
    /v1/instances/{instance_id}/applications:
        GET:
            tag: IDENTITYCENTER
