info:
    version: ""
    title: data_source_huaweicloud_workspace_application_rule_restriction_setting
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-center/app-rules/actions/get-rule-restriction:
        GET:
            tag: Workspace
