info:
    version: ""
    title: data_source_huaweicloud_identitycenter_application_providers
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IDENTITYCENTER
paths:
    /v1/application-providers:
        GET:
            tag: IDENTITYCENTER
