info:
    version: ""
    title: resource_huaweicloud_cts_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CTS
paths:
    /v3/{project_id}/configuration:
        GET:
            tag: CTS
        PUT:
            tag: CTS
