info:
    version: ""
    title: resource_huaweicloud_workspace_app_application_batch_publish
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-groups/{app_group_id}/apps:
        POST:
            tag: Workspace
