info:
  version: 
  title: resource_huaweicloud_apig_environment
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: APIG
paths:
  /v2/{project_id}/apigw/instances/{instanceId}/{path}/{id}:
    delete:
      tag: APIG
      operationId: Delete
    put:
      tag: APIG
      operationId: Update
  /v2/{project_id}/apigw/instances/{instanceId}/{path}:
    get:
      tag: APIG
      operationId: List
    post:
      tag: APIG
      operationId: Create
