info:
    version: ""
    title: resource_huaweicloud_hss_setting_two_factor_login_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/setting/two-factor-login/config:
        PUT:
            tag: HSS
