info:
    version: ""
    title: resource_huaweicloud_identitycenter_sso_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IdentityCenter
paths:
    /v1/instances/{instance_id}/sso-configuration:
        GET:
            tag: IdentityCenter
        POST:
            tag: IdentityCenter
