info:
  version: 
  title: resource_huaweicloud_fgs_async_invoke_configuration
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: FunctionGraph
paths:
  /v2/{project_id}/fgs/functions/{functionUrn}/async-invoke-config:
    delete:
      tag: FunctionGraph
      operationId: DeleteAsyncInvokeConfig
    get:
      tag: FunctionGraph
      operationId: GetAsyncInvokeConfig
    put:
      tag: FunctionGraph
      operationId: UpdateAsyncInvokeConfig
