info:
    version: ""
    title: resource_huaweicloud_workspace_app_application_batch_action
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-groups/{app_group_id}/apps/actions/disable:
        POST:
            tag: Workspace
    /v1/{project_id}/app-groups/{app_group_id}/apps/actions/enable:
        POST:
            tag: Workspace
