info:
    version: ""
    title: resource_huaweicloud_workspace_assist_auth_configuration_object_management
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v2/{project_id}/assist-auth-config/apply-objects:
        GET:
            tag: Workspace
        POST:
            tag: Workspace
