info:
    version: ""
    title: resource_huaweicloud_workspace_log_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v2/{project_id}/user-events/lts-configurations:
        GET:
            tag: Workspace
        POST:
            tag: Workspace
