info:
  version: 
  title: resource_huaweicloud_as_configuration
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: AS
paths:
  /autoscaling-api/v1/{project_id}/scaling_configuration/{id}:
    delete:
      tag: AS
      operationId: Delete
    get:
      tag: AS
      operationId: Get
  /autoscaling-api/v1/{project_id}/scaling_configuration:
    post:
      tag: AS
      operationId: Create
  /autoscaling-api/v1/{project_id}/scaling_group:
    get:
      tag: AS
      operationId: List
