info:
    version: ""
    title: resource_huaweicloud_identitycenter_application_instance_profile_delete
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IdentityCenter
paths:
    /v1/instances/{instance_id}/application-instances/{application_instance_id}/profiles/{profile_id}:
        DELETE:
            tag: IdentityCenter
