info:
    version: ""
    title: resource_huaweicloud_workspace_application_batch_authorize
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-center/apps/actions/batch-assign-authorization:
        POST:
            tag: Workspace
