info:
    version: ""
    title: resource_huaweicloud_workspace_application_rule_restriction_setting
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-center/app-rules/actions/set-rule-restriction:
        POST:
            tag: Workspace
