info:
  version: 
  title: resource_huaweicloud_apig_application
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: APIG
paths:
  /v2/{project_id}/apigw/instances/{instanceId}/apps/secret/{appId}:
    put:
      tag: APIG
      operationId: ResetAppSecret
  /v2/{project_id}/apigw/instances/{instanceId}/apps/{appId}/app-codes/{codeId}:
    delete:
      tag: APIG
      operationId: RemoveAppCode
  /v2/{project_id}/apigw/instances/{instanceId}/apps/{appId}/app-codes:
    get:
      tag: APIG
      operationId: ListAppCode
    post:
      tag: APIG
      operationId: CreateAppCode
  /v2/{project_id}/apigw/instances/{instanceId}/apps/{appId}:
    delete:
      tag: APIG
      operationId: Delete
    get:
      tag: APIG
      operationId: Get
    put:
      tag: APIG
      operationId: Update
  /v2/{project_id}/apigw/instances/{instanceId}/apps:
    post:
      tag: APIG
      operationId: Create
