info:
    version: ""
    title: resource_huaweicloud_workspace_application
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-center/apps:
        GET:
            tag: Workspace
        POST:
            tag: Workspace
    /v1/{project_id}/app-center/apps/{id}:
        DELETE:
            tag: Workspace
        PATCH:
            tag: Workspace
