info:
    version: ""
    title: resource_huaweicloud_apig_environment_variable
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/env-variables:
        GET:
            tag: APIG
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/env-variables/{env_variable_id}:
        DELETE:
            tag: APIG
        GET:
            tag: APIG
        PUT:
            tag: APIG
