# This is a lint workflow for documentation and example to help you get started with Actions
name: doc-lint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    paths:
    - 'docs/**'
    - 'examples/**'
    - '*.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "markdownlint"
  markdownlint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs actions-markdownlint
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files:
            ./docs/**/*.md
