# This is a lint workflow for documentation and example to help you get started with Actions
name: doc-lint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    paths:
    - 'docs/**'
    - 'examples/**'
    - '*.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "markdownlint"
  markdownlint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs actions-markdownlint
      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files:
            ./*.md ./examples ./docs

  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint

    - name: Show version
      run: tflint --version

    - name: Run TFLint
      run: |
        # Go through all dirs
        WORK_DIR="./examples"
        dirs=$(ls -d ${WORK_DIR}/*)
        for sub_dir in ${dirs}; do
          targets=$(ls -d ${sub_dir}/*)
          for DIRECTORY in ${targets}; do
            echo -e "\nlinting directory: ${DIRECTORY}"
            tflint -c ${WORK_DIR}/.tflint.hcl ${DIRECTORY}
          done
        done
