name: Mirror to HuaweiCloud codehub Repo
on:
  schedule:
    # triggers the workflow every day at 3:30 UTC.
    - cron:  '30 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  to_codehub:
    if: ${{github.repository == 'huaweicloud/terraform-provider-huaweicloud'}}
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@codehub.devcloud.cn-north-4.huaweicloud.com:3333300012/terraform-provider-huaweicloud.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.TF_MIRROR_PRIVATE_KEY }}
